% -*-texinfo-*-
\def\niceracronym#1{#1}
%\def\rmdefault{ppl}\def\ne{\mathrel{\not{}\mskip-8mu=}}\input pstexinfo
\input texinfo
@let@acronym@niceracronym

@c 	$Id$	

@c======================================================================@>
@c    pp3.texi - Part of the PP3 Program                                @>
@c    Copyright 2002, 2003 Torsten Bronger                              @>
@c                         <bronger@users.sourceforge.net>              @>
@c                                                                      @>
@c  This program may be distributed and/or modified under the           @>
@c  conditions of the MIT licence with the following contraint:         @>
@c  If you copy or distribute a modified version of this Software, the  @>
@c  entire resulting derived work must be given a different name and    @>
@c  distributed under the terms of a permission notice identical to     @>
@c  this one.                                                           @>
@c                                                                      @>
@c  Permission is hereby granted, free of charge, to any person         @>
@c  obtaining a copy of this software and associated documentation      @>
@c  files (the ``Software''), to deal in the Software without           @>
@c  restriction, including without limitation the rights to use, copy,  @>
@c  modify, merge, publish, distribute, sublicense, and/or sell copies  @>
@c  of the Software, and to permit persons to whom the Software is      @>
@c  furnished to do so, subject to the following conditions:            @>
@c                                                                      @>
@c      The above copyright notice and this permission notice shall be  @>
@c      included in all copies or substantial portions of the           @>
@c      Software.                                                       @>
@c                                                                      @>
@c      If you copy or distribute a modified version of this Software,  @>
@c      the entire resulting derived work must be given a different     @>
@c      name and distributed under the terms of a permission notice     @>
@c      identical to this one.                                          @>
@c                                                                      @>
@c  The Software is provided ``as is'', without warranty of any kind,   @>
@c  express or implied, including but not limited to the warranties of  @>
@c  merchantability, fitness for a particular purpose and               @>
@c  noninfringement.  In no event shall the authors or copyright        @>
@c  holders be liable for any claim, damages or other liability,        @>
@c  whether in an action of contract, tort or otherwise, arising from,  @>
@c  out of or in connection with the Software or the use or other       @>
@c  dealings in the Software.                                           @>
@c======================================================================@>

@c %**start of header
@setchapternewpage odd
@setfilename pp3.info
@settitle PP3 @value{VERSION}
@documentencoding ISO-8859-1
@c %**end of header

@set VERSION 1.3.2
@set SHORTVERSION 132

@defindex el
@syncodeindex el cp

@macro PPTHREE {}
@acronym{PP3}
@end macro

@macro LaTeX {}
@tex
L@kern-.36em%
        {@setbox0=@hbox{T}%
         @vbox to@ht0{@hbox{@sevenrm A}@vss}%
        }%
        @kern-.15em%
        @TeX
@end tex
@ifnottex
La@TeX{}@c
@end ifnottex
@end macro

@macro keyword {name}
@code{\name\}
@end macro

@macro beforerefheading {}
@tex
@penalty-6000@vskip5ex
@end tex
@end macro

@macro afterrefheading {}
@tex
@vskip-8ex@leavevmode
@end tex
@end macro

@macro s {}
@tex
@kern0.1667em%
@end tex
@end macro

@copying
This manual is for @PPTHREE{} (version @value{VERSION}),
which is a celestial charts drawing tool.

Copyright @copyright{} 2003 Torsten Bronger
@t{<}@email{bronger@@users.sourceforge.net}@t{>}.


@quotation
This documentation is free software; you can redistribute it and/or
modify it under the terms of the @acronym{MIT} licence.  Please see the
@t{COPYING} file of the @PPTHREE{} distribution for further information.
@end quotation
@end copying

@finalout
@titlepage
@title PP3
@subtitle drawing beautiful celestial maps
@subtitle version @value{VERSION}
@author Torsten Bronger, RWTH Aachen
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@dircategory Individual utilities
@direntry
* PP3: (PP3).   Drawing celestial maps.
@end direntry

@iftex
@hyphenation{}
@end iftex


@ifnottex
@node Top
@top The PP3 program for drawing celestial maps.

@PPTHREE{} generates celestial charts of high (typo)graphical quality.
It uses @LaTeX{} + pstricks for this, so the end formats are
@acronym{EPS} and @acronym{PDF} (in contrast to mere bitmaps).

The program automatically avoids labels that overlap, and you can change
many parameters.  You can place arbitrary text on the map using the
flexibility of the LaTeX language.

@menu
* Introduction::                The ideas behind it.
* Installation::                Some ways to set PP3 up.
* Usage::                       How to invoke PP3.
* Input scripts::               Telling PP3 what to do.
* Keywords reference::          List of all PP3 keywords.
* Data file formats::           Internal structure of the database files.
* Known problems::              List of known shortcomings and bugs.
* Index::                       General index.
@end menu
@end ifnottex

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@insertcopying
@end ifnottex


@node Introduction
@chapter Introduction


@menu
* What it is::                  Features of PP3.
* What it is not::              Limitations of PP3.
* The success of PP3::          Things that have been done using PP3.
* Basic astronomical terms::    
@end menu

@node What it is
@section What it is

There are many programs that can create stellar maps.  But none of them
reaches @PPTHREE{}'s typographic and graphical quality.  In contrast to
other programs @PPTHREE{} produces vector images
(e.@s{}g.@:@tie{}@acronym{PDFs}) rather than mere bitmaps.  Therefore it
is perfectly suited for creating illustrations for books or other print
media, and for web pages.

@PPTHREE{} is optimised for the semi-automatic generation of large sets
of sky maps.  It has decent default behaviour, however it can be
customised very flexibly.  It tries to take as much fine-tuning work
away from you as possible.


@node What it is not
@section What it is not

But I must also point out what @PPTHREE{} is @emph{not}.  It cannot help
you to professionally prepare your next observation night, nor is
@PPTHREE{} a visualisation tool for astronomical databases, with pop-up
window information for every sky object on the screen.

In fact, @PPTHREE{} not even has a graphical user interface.  So don't
expect any windows at all, and your mouse will be useless.  Instead,
@PPTHREE{} reads from one file and writes to another file.  (This is
done not only because its author was lazy but because it increases
efficiency, too.)  So, the program itself is quite stinted, but its
results are worth it!


@node The success of PP3
@section The success of @PPTHREE{}

@unnumberedsubsec Wikipedia

@begingroup
@rightskip0pt plus 1fil @PPTHREE{} has been used for the celestial maps
of all 88 constellations on @uref{http://www.wikipedia.org,Wikipedia},
the free encyclopedia.  Feel free to browse through a
@uref{http://wikipedia.org/w/wiki.phtml?title=List_of_constellations,list
of all constellations}.
@par
@endgroup

This is a web page, so you need bitmaps@footnote{as long as we don't
have @acronym{SVG}}, so a short @uref{http://www.gimp.org,Gimp}
script@footnote{which is included into the distribution} helped me to
convert @PPTHREE{}'s @acronym{EPS} vector output to @acronym{PNG}
bitmaps.  Additionally, this script creates smaller thumbnail version
for all charts that exceed a certain width.

The result is that one can create all maps plus their thumbnails with
one simple command call:

@example
make
@end example

@noindent
Surely it can't become simpler.  You may retort ``Well, but creating the
maps must have been the actual work''.  Of course it was, but first it
took only 10--15 minutes per map eventually, because much work is done
by the default behaviour of @PPTHREE{} itself.  And secondly:

@unnumberedsubsec French Wikipedia

Several months later the @uref{http://fr.wikipedia.org,French division
of Wikipedia} wanted to translate the maps to French.  They wanted
another background colour and French labels and constellation names.
They provided me with a translation table.  It took me three hours to
adjust the scripts, to run @file{make} again, and to upload the
@acronym{ZIP} file will all the demanded bitmaps.

@unnumberedsubsec h2g2

Originally @PPTHREE{} was written for a project on
@uref{http://www.bbc.co.uk/h2g2/guide/,h2g2}, an @emph{edited} Internet
encyclopedia.  Unfortunately the BBC editors wanted very small bitmaps
that would not have been helpful, and they were too lazy to include all
the 88@tie{}bitmaps.  So the project died, but on a smaller scale (for
ten constellations or so), it indeed motivated authors to constribute
articles about constellations.  The maps were externally linked.

@node Basic astronomical terms
@section Basic astronomical terms


@node Installation
@chapter Installation

You can get the latest @PPTHREE{} file releases from
@uref{http://sf.net/projects/pp3,@PPTHREE{}'s project page on
Sourceforge}.  The main @PPTHREE{} distrubution comes as several files,
namely

@table @file
@item pp3-@var{version}-win.zip
is the complete Windows distribution.

@item pp3-@var{version}-1tb.i386.rpm
is the complete Linux RPM distribution.  (There is also the
corresponding source RPM called @file{pp3-@var{version}-1tb.src.rpm}.)

@item pp3-@var{version}.tar.bz2
is the complete source distribution.

@item pp3-@var{version}-cripple.tar.gz
is a partial source distribution.  Milky Way, Nebulae, and the
@acronym{CWEB} source code are omitted.

@end table

@noindent
Obviously you need only @emph{one} of these files.

@menu
* Windows::                     Installation on Windows.
* Linux::                       Installation on Linux.
@end menu

@node Windows
@section Installation on Windows

Although @PPTHREE{} runs independently from other programs, it is not
useful when it's alone.  It needs two external tools in order to work
properly: @TeX{} and Ghostscript.  @emph{You need not know how to use
@TeX{} and Ghostscript!}

On most Unix/Linux systems @TeX{} and Ghostscript are already installed.
But on Windows, you have to install them yourself.  Fortunately this is
not difficult, and both programs may be useful for other puposes, too.

@menu
* Getting TeX::                 Installing the TeX typesetting engine.
* Getting Ghostscript::         Installing Ghostscript for Postscript
                                  handling.
* Installing PP3::              Finally installing PP3 itself.
@end menu

@node Getting TeX
@subsection Getting @TeX{}

@TeX{} is a mighty typesetter.  @PPTHREE{} calls @TeX{} in order to
actually create the stellar map.  The result is a Postscript file.

@begingroup
@rightskip0pt plus 1fil
There are two major @TeX{} variants for Windows, namely
@uref{http://www.miktex.org,Mik@TeX{}} and
@uref{http://www.tug.org/texlive/,@TeX{}@tie{}Live}.  Both are rather
similar in their functionality, and both come with a nice installation
tool.  Please assure that the @t{pstricks} package as part of @TeX{} is
installed, however this is highly probable anyway.
@par
@endgroup

@node Getting Ghostscript
@subsection Getting Ghostscript

@begingroup
@rightskip0pt plus 1fil
The best tool for dealing with Postscript files is
@uref{http://www.cs.wisc.edu/~ghost/doc/AFPL/get811.htm,Ghostscript}.
In particular, if you've installed Ghostscript, PP3 is able to generate
PDF files for you.  It is wise (although not necessary) to install
@uref{http://www.cs.wisc.edu/~ghost/gsview/get45.htm,GhostGum}, too.  It
lets you view arbitrary Postscript files on screen.
@par
@endgroup

@node Installing PP3
@subsection Installation of @PPTHREE{} itself

When @TeX{} and Ghostscript are in the right place, you finish the
installation by unpacking the @PPTHREE{} @acronym{ZIP} file and copying
its content in the proper directories:

@enumerate
@item
Copy @file{pp3.exe} to an arbitrary directory that is in your
@env{PATH}.

@item
Copy all the other files to @emph{one single} arbitary directory.  Then
set the environment variable @env{PP3DATA} to this directory.

@end enumerate

For the sake of simplicity, I recommend to copy everything to
@file{C:\Programs\pp3} and to set your @env{PATH} environment variable
to

@display
@code{@var{old PATH};C:\Programs\pp3}
@end display

@noindent
and to set the @env{PP3DATA} environment variable to
@file{C:\Programs\pp3}.  That's it.


@node Linux
@section Installation on Linux

@menu
* RPM installation::            The simple way.
* Building from sources::       The hard way.
@end menu

Before you install @PPTHREE{}, ensure that @TeX{} and Ghostscript are
installed.


@node RPM installation
@subsection @acronym{RPM} installation

You should consider to use the @acronym{RPM} file, because it is the
simplest installation.  It works for SuSE Linux and probably also for
Red@s{}Hat.  Just enter (as root)

@display
@code{rpm -i @var{RPM-file-name}}
@end display

@noindent
That's it.


@node Building from sources
@subsection Building from sources

(Actually you can compile the sources on Windows, too (of course), but
since most people who do compile are Linux users, I dare to put it in
the Linux section.)

@begingroup
@rightskip0pt plus 1fil @PPTHREE{} is written in @acronym{CWEB}@.  This
is special form of C++ and can be transformed to real C++ trivially.
You only need the
@uref{http://www-cs-faculty.stanford.edu/~knuth/cweb.html,@acronym{CWEB}
programs} installed.  For your convenience the C++ code of @PPTHREE{} is
included into the source distribution, so you need @acronym{CWEB} only
if you want to modify the program.
@par
@endgroup

There is no @file{configure} script.  Just call @code{make} and (as
root) @code{make install}.  Before that, you may want to adjust some
paths in the @file{Makefile}.

@PPTHREE{} looks for its data files (all files with the @file{.dat}
extension) in a special directory that is pre-compiled in the
executable.  The Makefile assures that this is the correct one, but you
can override that with the environment variable @env{PP3DATA}.


@node Usage
@chapter Usage

@menu
* Invokation::                  Starting PP3.
* Using pipes::                 If you really need pipes for some
                                  reason.
@end menu

@node Invokation
@section Starting PP3

Invoking @PPTHREE{} is very straightforward.  Since it is a command line
program you only have to call it somehow and give a so-called input
script as the parameter, see @ref{Input scripts}.  For example, entering

@example
pp3 orion.pp3
@end example

@noindent
on the command line starts @PPTHREE{} and lets it generate the file
@file{orion.pdf}, which is a @acronym{PDF} file with a star map of
Orion.  You can view this @acronym{PDF} with Acrobat Viewer, convert it
to a bitmap, or you can embed it into a text of yours.

To be honest, there are three possible output formats.  By default,
@PPTHREE{} generates a @LaTeX{} file in the current directory.  But most
people cannot do much with it, therefore certain commands in the input
script trigger @acronym{EPS} or @acronym{PDF} output.

@PPTHREE{} can't generate bitmaps.  If you need bitmaps you must use a
bitmap program (e.@s{}g.@: Corel Draw or the
@uref{http://www.gimp.org,Gimp}) for that.


@node Using pipes
@section Using pipes

Especially on Unix it is very common to read from standard input and to
write to standard output.  I don't think that this is sensible for
@PPTHREE{}, but anyway, I included this facility.  If you give
`@code{-}' as the only parameter, @PPTHREE{} reads the input script from
standard input, and if you don't give an output filename in the input
script (@pxref{Input scripts}), @PPTHREE{} writes to standard output.



@node Input scripts
@chapter Writing input scripts

On @uref{http://sf.net/projects/pp3,@PPTHREE{}'s project page} you can
download a neat reference card.  If you fold it twice it is a handy
zigzag.

@menu
* Minimal example::             The first four PP3 lines.
* More bells and wistles::      How to make it look more sophisticated.
@end menu


@node Minimal example
@section Minimal example input script

The minimal @PPTHREE{} input script is -- well -- the empty file.  Then
@PPTHREE{}'s default values create a dark blue star map of Orion.  You
can override these defaults step by step.  Let's do so: Write

@example
# Cygnus, the Swan

filename output swan.tex
switch pdf_output on

set center_rectascension  19.95
set center_declination    40.8
@end example

@noindent
to the file @file{swan.pp3} and call

@example
pp3 swan.pp3
@end example

@noindent
The result is a file @file{swan.pdf} in the current directory with a
star map of the Swan.

The lines of @file{swan.pp3} are not difficult to explain:  The very
first line is a comment.  Everything that starts with a @code{#} is a
comment.  You can write descriptive text in them to make the file more
readable.

The line

@example
filename output swan.tex
@end example

@noindent
makes @PPTHREE{} to write the generated map to the file
@file{swan.tex}.  But such a file is rarely the desired output.
Therefore the next line

@example
switch pdf_output on
@end example

@noindent
tells @PPTHREE{} that we want to have a @acronym{PDF} file.  So
@PPTHREE{} does everything necessary for that.  And finally,

@example
set center_rectascension  19.95
set center_declination    40.8
@end example

@noindent
denotes the area of the sky that we want to be displayed.  Both values
indicate the celestial point that we want to have in the centre of the
map.  In this case, 19.95@s{}h rectascension and @math{+40.8^\circ}
declination which is the centre of the constellation Swan.


@node More bells and wistles
@section More bells and wistles


@node Keywords reference
@chapter Kewords reference

@menu
* General structure::           
* Parameters::                  
* Objects and Labels::          
@end menu

@node General structure
@section General structure


@node Parameters
@section Setting Parameters


@node Objects and Labels
@section Setting or deleting celestial objects and their labels


@node Data file formats
@chapter Data file formats

Maybe you want to use you own data bases with @PPTHREE{}.  If they are
not too large@footnote{Unfortunately @PPTHREE{} still has the
disadvantageous behaviour of reading the @emph{whole} data base file.}
you may well do so.  Of course, then you need to know the internal
structure of the files.  Although they are so simple that reverse
engeneering should be almost trivial, you find here a complete
description of all of them.

Additionally I will give detailed information where the original data of
@PPTHREE{}'s standard distribution came from.

The last point, the ``label dimensions file'', isn't a real data base
file, but an internal temporary file.  It is mentioned here just for
completeness.

@menu
* Stars data file::             The stars database.
* Nebulae data file::           Galaxies, dust clouds, and such.
* Lines data file::             The purely subjective constellation
                                  lines.
* Boundaries data file::        The boundaries between constellations.
* Milky Way data file::         The Milky Way brightness bitmap.
* Label dimensions file::       Typographic diemsnions of all labels.
@end menu

@node Stars data file
@section Stars data file

This is a text file usually called @file{stars.dat}.  Four consecutive
lines belong together and refer to one particular star.  There is no
header.

@table @asis
@item Line 1
A row with seven fields separated by whitespace:

@enumerate
@item
Henry Draper Catalogue number (`@code{0}' if unknown),

@item 
BSC catalogue number (`@code{0}' if unknown),

@item
rectascension in hours,

@item
declination in degrees,

@item
visual brightness in magnitudes,

@item
B@math{-}V brightness in magnitudes (`@code{99.0}' if unknown), and

@item
Flamsteed number (`@code{0}' if unknown).

@end enumerate

@item Line 2
The label (astronomical name) for the star, as a @LaTeX{}-ready string,
e.@s{}g.@: ``@code{$\alpha$}'', ``@code{$\phi^{2}$}'', or simply
``@code{$23$}''.  May be the empty string.

@item Line 3
The astronomical abbreviation of the constellation.  It must be all
uppercase.

@item Line 4
The spectral class.  It must start with the spectral class letter,
followed by the fraction digit, followed by the luminosity class as a
Roman number, e.@s{}g.@: ``@code{F5III}''.  Anything may follow as in
``@code{K2-IIICa-1}'', however the mandatory parts must not contain any
whitespace.

@end table

@subheading Example

@smallexample
358 15 0.139805 29.0906 2.06 -0.11 21
$\alpha$
AND
B8IVpMnHg
11636 553 1.91067 20.8081 2.64 0.13 6
$\beta$
ARI
A5V
886 39 0.220611 15.1836 2.83 -0.23 88
$\gamma$
PEG
B2IV
@end smallexample


@node Nebulae data file
@section Nebulae data file


This is a text file usually called @file{nebulae.dat}.  There is no
header.  The file is just a whitespace separated stream of numbers and
constellation abbreviations.  In order to make it more readable though,
the standard @PPTHREE{} nebulae file has every nebula on one single line
of its own.

Each dataset has the following ten fields:

@enumerate
@item
@acronym{NGC} catalogue number (`@code{0}' is not listed there),

@item
@acronym{IC} catalogue number(`@code{0}' is not listed there),

@item
Messier Catalogue number(`@code{0}' is not listed there),

@item
The astronomical abbreviation of the constellation.  It must be all
uppercase.

@item
rectascension in hours,

@item
declination in degrees,

@item
visual brightness in magnitudes,

@item
large diameter in degree minutes,

@item
small diameter in degree minutes (must be equal to the large diameter if
unknown), and

@item
the horizontal angle if the large diameter in degrees (`@code{720.0}' if
unknown).

@end enumerate

@subheading Example

@smallexample
1 0 0 PEG 0.121083 27.7089 13.6 0.0283333 0.02 -30 1
2 0 0 PEG 0.121417 27.6786 15 0.0166667 0.01 -22 1
3 0 0 PSC 0.121333 8.30139 14.4 0.0183333 0.01 -21 1
4 0 0 PSC 0.123472 8.37389 16.9 0.01 0.005 55 1
5 0 0 AND 0.130222 35.3628 14.8 0.02 0.0116667 -25 1
6 0 0 AND 0.159056 33.3089 14.1 0.0283333 0.0266667 -50 1

1976 0 42 ORI 5.58808 -5.39028 4 1.08333 1 720 2
3034 0 82 UMA 9.93167 69.6831 9.2 0.186667 0.0716667 25 1
7000 0 0 CYG 20.9806 44.5167 4 2 1.66667 720 2
@end smallexample


@node Lines data file
@section Constellation lines data file

This is a text file usually called @file{lines.dat}.  It has no header.
You can define paths of constellation lines by lists of stars that are
ended with a semicolon@tie{}`@code{;}'.  You can insert superfluous
whitespace as you wish, and comments after every@tie{}`@code{#}'.

Stars are given in the usual way: Either by a pair of constellation
abbreviation and Flamsteed number, as in

@example
ORI 19
@end example

@noindent
(Rigel), or by `@code{HD}' and the Henry Draper catalogue number, as in

@example
HD 108248
@end example

@noindent
(Acrux).

@subheading Example

@smallexample
# Orion

ORI 19  ORI 34  ORI 24 ;
ORI 53  ORI 50  ORI 46  ORI 34 ;
ORI 50  ORI 58 ;

# Southern Cross

HD 111123  # beta Cru
HD 106490 ; # delta Cru

HD 108248  # alpha Cur
HD 108903 ;  # gamma Cru
@end smallexample


@node Boundaries data file
@section Boundaries data file

It doesn't make much sense to use an own boundaries file, unless you
want to use a different equinox, but anyway.  This is a text file
usually called @file{boundaries.dat}.  It has no header.

The file is a sequence of elementary line segments.  Every segment is a
whitespace separated sequence of entries.  The entries for each segment
are:

@enumerate
@item
Number of points @math{n_1} in the segment.

@item
Repeated @math{n_1} times:

@enumerate
@item
rectascension of point in hours,
@item
declination of point in
degrees.
@end enumerate

@item
Number of constellations @math{n_2} touching this border line (is
always@tie{}2, however it hasn't always been due to flawed raw data).

@item
Repeated @math{n_2} times: All uppercase astronomical abbreviation of
the adjacent constellation. It may distinguish between @code{SER1} and
@code{SER2} for Serpens Caput and Serpens Cauda.

@end enumerate

@subheading Example

@smallexample
3 20.63865 2.43608 20.63929 1.43613 20.63992 0.43617 2 AQL AQR
10 20.63992 0.43617 20.64055 -0.56377 20.64118 -1.56373
  20.64181 -2.56368 20.64245 -3.56364 20.64308 -4.56359 20.64372 -5.56355
  20.64435 -6.56350 20.64500 -7.56346 20.64564 -8.56341 2 AQL AQR
9 17.71838 -67.57110 17.65152 -67.58319 17.58465 -67.59526
  17.51772 -67.60731 17.45076 -67.61933 17.38378 -67.63130 17.31676 -67.64324
  17.24970 -67.65515 17.21616 -67.66108 2 ARA APS
@end smallexample



@node Milky Way data file
@section Milky Way data file

This is a text file usually called @file{milkyway.dat}.

Its header is extremely simple: It consists of only one number which is
the maximal (=@tie{}equatorial) diagonal half distance of two pixels in
degrees (double). This value is used as the radius for the milky way
pixels.  Of course it must be the minimal radius for which there are no
gaps between the pixels.

What follows are the Milky Way pixels themselves.  Each consists of tree
entries, separated by white space:

@enumerate
@item
The rectascension in hours,

@item
the declination in degrees, and

@item
the grey value of the pixel from 1@tie{}to@tie{}255.  Zero is not used
because zero-value pixels are not included into the data file anyway.
@end enumerate


@subheading Example

@smallexample
0.212
11.885 0.259 1
11.962 0.295 5
11.974 0.298 5

17.982 -26.999 136
17.982 -27.299 158
17.982 -27.599 169
17.982 -27.899 199
17.981 -28.199 235
@end smallexample


@node Label dimensions file
@section Label dimensions file

This file is never user provided but generated by @PPTHREE{} itself in
order to store typographic dimensions of all labels.  Highly probably
you needn't know its structure.

Every labels has two lines in the file:

@table @asis
@item Line 1
The label itself in @LaTeX{} form.

@item Line 2
The typographic width, height, and depth of the label in centimetres,
separated by whitespace.

@end table

@subheading Example

@smallexample
$10$~\footnotesize UMa
0.97106 0.23043 0.00253
$\omega$
0.34197 0.17081 0.00000
10 UMa
1.11657 0.23389 0.00316
47 Tuc
0.94506 0.23389 0.00316
Pleiades
1.20865 0.24777 0.00316
\FlexLabel@{Andromeda@}
1.86061 0.25076 0.00316
\FlexLabel@{Antlia@}
0.93945 0.25076 0.00316
@end smallexample


@node Known problems
@chapter Known problems



@node Index
@unnumbered Index

@iftex
All @PPTHREE{} keywords are printed in @t{typewriter} style.
@end iftex

@printindex cp

@bye

